### ISSUE TITLE
Issue with socolissimo module

### ISSUE THREAD

**Issue by Elitius** [PrestaShop/socolissimo#19]
Hi,

I got this message after select "Colissimo" carrier in order tunnel.

Liste des erreurs Colissimo :
This key is required for Socolissimo:CECIVILITY
This key is required for Socolissimo:CEFIRSTNAME
This key is required for Socolissimo:CEADRESS3
This key is required for Socolissimo:CEZIPCODE
This key is required for Socolissimo:CETOWN
This key is required for Socolissimo:DELIVERYMODE
This key is required for Socolissimo:CEEMAIL

How can I correct this issue ?
Thanks

**Comment by quadrateam** [comment]
Hi,

You have those errors messages because you forgot to configure your mobile part in your account in back office colisposte.

For more detais please to the manuel (page 6). 
You can download it from that page : 
http://shop.quadra-informatique.fr/fr/modules-gratuits/34-colissimo-simplicite-prestashop.html

Regards

**Comment by Elitius** [comment]
Hi,

I know, but I have strictly the same configuration on Prestashop and Coliposte BO.

-- 
Simon

Le 18 mars 2016 à 10:03:25, Quadra Informatique (notifications@github.com) a écrit:

Hi,

You have those errors messages because you forgot to configure your mobile part in your account in back office colisposte.

For more detais please to the manuel (page 6).
You can download it from that page :
http://shop.quadra-informatique.fr/fr/modules-gratuits/34-colissimo-simplicite-prestashop.html

Regards

**Comment by quadrateam** [comment]
Hi,

What is your version of the module and the version of Prestashop ?

Regards

**Comment by quadrateam** [comment]
_Close tickets without response._

**Comment by maximekiteshop** [comment]
Hii Quadrateam, i have the same issue than Elitius even if i configured the mobile part in my coliposte account  and I donwload the last version of colissimo simplicite module.  What other thing i can do to resolve it ?
Still, thank you for amazing work.

**Comment by quadrateam** [comment]
Hi maximekiteshop,

Please first check that : 
- BO colisposte is filled for desktop and mobile.
- BO prestashop is filled too and matches with informations on BO colisposte.

Regards,
