### ISSUE TITLE
Problème "key is required"

### ISSUE THREAD

**Issue by azriel49** [PrestaShop/socolissimo#20]
Bonjour,

Après avoir installé et configurer le module sur un Prestashop 1.6.1.6 je tombe systématiquement sur cette erreur après avoir sélectionné le transporteur : 

`Liste des erreurs Colissimo :
This key is required for Socolissimo:CECIVILITY
This key is required for Socolissimo:CEFIRSTNAME
This key is required for Socolissimo:CEADRESS3
This key is required for Socolissimo:CEZIPCODE
This key is required for Socolissimo:CETOWN
This key is required for Socolissimo:DELIVERYMODE
This key is required for Socolissimo:CEEMAIL`

J'ai vérifié la configuration mobile sur le site soColissimo, elle est la même que la partie desktop.
Le module est également correctement configuré dans le backoffice prestashop.

Avez-vous une piste ?

Cordialement,
Nicolas

**Comment by azriel49** [comment]
A noter que tous les champs partant vers "http://ws.colissimo.fr/pudo-fo-frame/storeCall.do" on l'air d'être correctement rempli.
soColissimo revient tout de même vers le script de validation, avec les champs ci dessus manquants.
Le souci viendrait de soColissimo lui même ?

**Comment by quadrateam** [comment]
Bonjour,

Ces derniers temps l'api de la poste a eu des soucis d'authentification pour certains clients qui generait des erreurs de votre type.

Pourriez vous dumper $_GET dans le fichier validation.php du module et me dire ce que vous voyez ? Ne transmettez pas les champs PUDOFOID dans votre réponse il est confidentiel.

Bien cordialement,

**Comment by azriel49** [comment]
Bonjour,

merci de votre réponse, il semblerait en effet que cela vienne d'un souci sur l'api de la poste car le problème semble corrigé maintenant.

Je ferme donc ce ticket pour le moment en vous remerciant d'avoir pris le temps de me répondre.
